### ISSUE TITLE
JEI version required issue/question

### ISSUE THREAD

**Issue by Ravalli03** [p455w0rd/JustEnoughEnergistics#1]
I tried using ver. 1.0.2 but it requires a newer (Beta) version of JEI which has a few bugs in it. Is there anyway to use this mod with the latest (Release) version of JEI? Thanks.

**Comment by p455w0rd** [comment]
can u tell me if it's good with the most recent JEI version?
I'd much rather not revert

**Comment by Ravalli03** [comment]
I'll give it a try
