### ISSUE TITLE
Recipie conflict - Stone Wand from Better Builder's Wands, Building Tool from Structurize

### ISSUE THREAD

**Issue by generilisk** [p455w0rd/JustEnoughEnergistics#2]
Both items have the following recipe, where C is cobblestone, S is stick:
```
  C
 S 
S  
```
The Building Tool takes priority, so the stone wand cannot be crafted.

**Comment by Bennyboy1695** [comment]
That's a recipe conflict which is an issue with the pack your playing, not this mod.

**Comment by generilisk** [comment]
I apologize, Too many tabs open. My mistake.
