### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Sunekaer** [p455w0rd/JustEnoughEnergistics#3]
"When trying to add the JEI recipe of Nether Quartz Dust in a SAG Mill in the pattern terminal, the game crashes."

https://paste.feed-the-beast.com/view/5f88b409
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/190

**Comment by p455w0rd** [comment]
Thank you for the report! Fixed version is live :) https://minecraft.curseforge.com/projects/just-enough-energistics-jee/files/2662093
