### ISSUE TITLE
Autofill oredict recipe fills with wildcard metadata

### ISSUE THREAD

**Issue by codewarrior0** [p455w0rd/JustEnoughEnergistics#6]
![image](https://user-images.githubusercontent.com/307683/51508354-dfe3e600-1d98-11e9-82ea-8ad939afd442.png)

Recipe uses `<ore:sand>` as an input, and Forge creates that oredict key with a single item which has wildcard metadata.

JustEnoughEnergistics-1.12.2-1.0.5.jar

**Comment by p455w0rd** [comment]
well..so much for what I was tryin to do lol...next push will have this fixed once and for all...bit of code efficiency implemented as well
