### ISSUE TITLE
JEE in Multiplayer

### ISSUE THREAD

**Issue by Cookiemonst3rr** [p455w0rd/JustEnoughEnergistics#8]
I'm trying to add JEE to my FTB Revelations server. I startup the server with the mod installed and it just crashes before any mods load. It works perfectly fine in singleplayer.

**Comment by p455w0rd** [comment]
Have patience

**Comment by Cookiemonst3rr** [comment]
I'm terribly sorry, I saw that the github wasn't very active so I didn't know if I would get a response.
