### ISSUE TITLE
Prioritize pure crystals over raw crystals when making patterns

### ISSUE THREAD

**Issue by thermotto** [p455w0rd/JustEnoughEnergistics#9]
**Issue**
Normally AE2 will prioritize using pure crystals over the raw form when clicking + in JEI to create a pattern. With JEE it always uses the raw form.

**Expected behavior**
For example the ME Glass Cable can be made with two fluix crystals in any combination of raw or pure form. Clicking the + in JEI will use pure crystals in the pattern first if they are available (or can be crafted).

**Steps to replicate**
1. Open ME Pattern Terminal
2. Make sure that pure fluix crystals are either available or can be crafted
3. Locate and open recipe for ME Glass Cable in JEI
4. Click + to apply recipe
5. Pattern in terminal uses raw crystals instead of pure

**Images**
JEI recipe:
![JEI recipe](https://user-images.githubusercontent.com/50426832/58345641-d5a92580-7e26-11e9-9a22-79186f8f9a67.png)

Pattern without JEE:
![Pattern without JEE](https://user-images.githubusercontent.com/50426832/58345678-e6599b80-7e26-11e9-976e-7e9bf29bd0ed.png)

Pattern with JEE:
![Pattern with JEE](https://user-images.githubusercontent.com/50426832/58345662-df328d80-7e26-11e9-9c9e-c156cef2a615.png)

**Note**
This is only in the Pattern Terminal. In the Crafting Terminal it will correctly use pure crystals first.

**Info**
Minecraft verion: 1.12.2
Forge version: 14.23.5.2831
JEE version: 1.12.2-1.0.6
Modpack: Sky Factory 4 v4.0.5 (also encountered in Enigmatica 2 Expert)
Java version: 8u211

**Comment by p455w0rd** [comment]
I will make a config option for this

**Comment by thermotto** [comment]
Thanks for the fast response! I really appreciate what JEE does for AE2. Hopefully someday it could be integrated into AE2.

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/just-enough-energistics-jee/files/2726897
